In [2]:
import pandas as pd
from pymongo import MongoClient

In [3]:
client = MongoClient("mongodb://localhost:27017/")
collection = client["poetry"]["books"]

In [4]:
df = pd.DataFrame(collection.find({}))
df.head()

,_id,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,...,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
0,69e8ac2044e2f3dc8aa255a6,,1,[],US,eng,"[{'count': '8', 'name': 'to-read'}, {'count': ...",,false,3.83,...,11,,1887,https://www.goodreads.com/book/show/16037549-v...,https://images.gr-assets.com/books/1348176637m...,16037549,3,5212748,Vision of Sir Launfal and Other Poems,Vision of Sir Launfal and Other Poems
1,69e8ac2044e2f3dc8aa255a7,0811223981,2,[],US,,"[{'count': '100', 'name': 'to-read'}, {'count'...",,false,3.83,...,4,,2015,https://www.goodreads.com/book/show/22466716-f...,https://images.gr-assets.com/books/1404958407m...,22466716,37,41905435,Fairy Tales: Dramolettes,Fairy Tales: Dramolettes
2,69e8ac2044e2f3dc8aa255a8,0374428115,7,[],US,,"[{'count': '32', 'name': 'to-read'}, {'count':...",,false,4.38,...,7,,2008,https://www.goodreads.com/book/show/926662.Gro...,https://s.gr-assets.com/assets/nophoto/book/11...,926662,45,911665,Growltiger's Last Stand and Other Poems,Growltiger's Last Stand and Other Poems
3,69e8ac2044e2f3dc8aa255a9,0156182890,12,[],US,,"[{'count': '554', 'name': 'to-read'}, {'count'...",,false,3.71,...,3,,1964,https://www.goodreads.com/book/show/926667.The...,https://images.gr-assets.com/books/1382939971m...,926667,115,995066,The Cocktail Party,The Cocktail Party
4,69e8ac2044e2f3dc8aa255aa,1942004192,4,[],US,eng,"[{'count': '228', 'name': 'to-read'}, {'count'...",,false,5.00,...,12,First,2015,https://www.goodreads.com/book/show/29065952-l...,https://images.gr-assets.com/books/1455198396m...,29065952,9,49294781,Louder Than Everything You Love,Louder Than Everything You Love

In [5]:
collection_genre = client["goodreads"]["genres"]

In [6]:
books_ids = pd.DataFrame(list(collection.find({},
                                              {"book_id":1, "_id":0}
                                              )))

In [7]:
books_ids.shape

(36514, 1)

In [8]:
books_ids.head()

    book_id
0  16037549
1  22466716
2    926662
3    926667
4  29065952

In [9]:
books_ids = books_ids["book_id"].tolist()

In [10]:
books_ids

['16037549',
 '22466716',
 '926662',
 '926667',
 '29065952',
 '35235890',
 '15861988',
 '9495428',
 '346381',
 '598195',
 '24849837',
 '554372',
 '20544060',
 '10898316',
 '17510247',
 '2067880',
 '213181',
 '17729612',
 '250810',
 '11739266',
 '8077005',
 '35288488',
 '6100815',
 '24874449',
 '17227009',
 '2260201',
 '269677',
 '1828412',
 '3864107',
 '17562598',
 '6635610',
 '34381389',
 '13423864',
 '3816201',
 '1388854',
 '2009619',
 '9572160',
 '1286592',
 '6202812',
 '773136',
 '11385118',
 '25100138',
 '1739707',
 '11793659',
 '13494092',
 '17284121',
 '25490630',
 '10427087',
 '24820659',
 '4204521',
 '6603057',
 '752936',
 '25402546',
 '3658489',
 '18858148',
 '25384853',
 '28088033',
 '17333426',
 '16186963',
 '7517330',
 '1207466',
 '18336230',
 '551357',
 '9719801',
 '32022138',
 '2408028',
 '55427',
 '24940289',
 '12396002',
 '1840718',
 '1499640',
 '1499648',
 '2599816',
 '26848169',
 '20631997',
 '849845',
 '20262357',
 '18406193',
 '18406197',
 '1545160',
 '6411796',
 '17229678',
 '3385038',
 '3052316',
 '33931056',
 '820475',
 '820474',
 '10311528',
 '23497828',
 '34608938',
 '13212950',
 '27409580',
 '11390422',
 '563117',
 '96910',
 '9182566',
 '10438957',
 '17824924',
 '17437209',
 '7328221',
 '10589071',
 '13399473',
 '25969873',
 '10046700',
 '18748766',
 '13558836',
 '22663880',
 '12429335',
 '26831641',
 '1520244',
 '1939787',
 '678825',
 '7113632',
 '26165692',
 '1917087',
 '375893',
 '2442582',
 '11517452',
 '30989405',
 '11399139',
 '765987',
 '15829794',
 '1222347',
 '17324134',
 '29869936',
 '3137572',
 '397019',
 '17861288',
 '1298073',
 '10506571',
 '22727911',
 '30984227',
 '15770114',
 '12156125',
 '169070',
 '677952',
 '1990488',
 '29545462',
 '704915',
 '704917',
 '1173087',
 '475003',
 '20563083',
 '1849948',
 '10250238',
 '9368172',
 '3130834',
 '2694953',
 '21896506',
 '6554190',
 '2701',
 '6657114',
 '493359',
 '36333521',
 '6004176',
 '25060281',
 '1190701',
 '28926132',
 '1501849',
 '1233859',
 '1489946',
 '1676943',
 '1171423',
 '1504664',
 '3565588',
 '21363357',
 '197986',
 '28481692',
 '9466037',
 '18624885',
 '16187882',
 '6590725',
 '743646',
 '1515020',
 '344344',
 '1335224',
 '886017',
 '6438915',
 '30072542',
 '10404643',
 '13519197',
 '8812416',
 '17406722',
 '6435705',
 '396581',
 '9615870',
 '129658',
 '1140164',
 '382075',
 '3184065',
 '13647986',
 '8175403',
 '2355014',
 '10402730',
 '8620591',
 '1672141',
 '75493',
 '75496',
 '75497',
 '75494',
 '75495',
 '113209',
 '20470799',
 '50068',
 '4361538',
 '12389347',
 '26001310',
 '22461190',
 '4592127',
 '12309808',
 '17231953',
 '7107083',
 '11295329',
 '470503',
 '12675105',
 '15189170',
 '15189171',
 '6619037',
 '152532',
 '152530',
 '152535',
 '15777397',
 '15777398',
 '17800801',
 '34114258',
 '2928309',
 '6383302',
 '6383306',
 '1573351',
 '1797237',
 '18215664',
 '6508048',
 '15573925',
 '8429303',
 '25349217',
 '29855394',
 '98390',
 '13298184',
 '9947556',
 '6707931',
 '694475',
 '393866',
 '22291540',
 '2621475',
 '18482526',
 '5997878',
 '1278093',
 '141600',
 '3999493',
 '12027057',
 '516650',
 '12438482',
 '31697135',
 '418216',
 '6356660',
 '15771798',
 '19674780',
 '8358980',
 '29932350',
 '251121',
 '9432234',
 '15790207',
 '1561019',
 '1103978',
 '8488725',
 '22752655',
 '836062',
 '743972',
 '18192125',
 '3930919',
 '47180',
 '18490555',
 '405238',
 '15849609',
 '25731868',
 '30423283',
 '12011051',
 '7786942',
 '18109404',
 '8340952',
 '20327334',
 '6870005',
 '31208742',
 '9968063',
 '8131481',
 '18307006',
 '1055873',
 '6580847',
 '21411190',
 '998064',
 '518246',
 '13629111',
 '27069781',
 '633627',
 '2359345',
 '16090292',
 '13572380',
 '34376890',
 '936208',
 '936209',
 '936207',
 '23015378',
 '25378291',
 '24906265',
 '1971154',
 '1971153',
 '27625946',
 '303508',
 '3669893',
 '27778116',
 '6313904',
 '74534',
 '18591254',
 '218985',
 '35394156',
 '486085',
 '567011',
 '1657005',
 '1160501',
 '12713072',
 '17332882',
 '2951693',
 '16700063',
 '324389',
 '2430716',
 '1515387',
 '325698',
 '25586865',
 '33950809',
 '9311644',
 '6164314',
 '2715832',
 '7146618',
 '10749192',
 '523957',
 '6819632',
 '1371350',
 '6134973',
 '224300',
 '9110875',
 '1647386',
 '35435558',
 '23492069',
 '11845422',
 '623185',
 '13630583',
 '1453838',
 '2213236',
 '1396606',
 '1292895',
 '1292896',
 '1292899',
 '11890081',
 '13108509',
 '18002178',
 '865204',
 '5966818',
 '1905422',
 '1807341',
 '857449',
 '6984846',
 '732354',
 '1222469',
 '13586882',
 '250048',
 '29224035',
 '15635',
 '14523564',
 '24796277',
 '18367837',
 '5098314',
 '14943875',
 '1360373',
 '18075374',
 '5269911',
 '13259644',
 '144101',
 '28347334',
 '4803601',
 '13586667',
 '7953223',
 '1721405',
 '9430304',
 '23941430',
 '432164',
 '1407969',
 '6324818',
 '25527249',
 '20979101',
 '1496385',
 '161430',
 '417782',
 '25785774',
 '12559320',
 '18336159',
 '593786',
 '15903019',
 '8805803',
 '752886',
 '18901',
 '825647',
 '3824832',
 '463016',
 '2353702',
 '11872363',
 '24977055',
 '3295509',
 '25194384',
 '8729193',
 '24890269',
 '1333840',
 '603963',
 '10154769',
 '860818',
 '11550450',
 '14290949',
 '1454842',
 '12143095',
 '6146024',
 '21608751',
 '3611264',
 '28515389',
 '15749511',
 '743715',
 '1639650',
 '18284560',
 '789667',
 '873462',
 '659775',
 '1991879',
 '435060',
 '435061',
 '435063',
 '852662',
 '21219304',
 '2764176',
 '226946',
 '8417025',
 '14061264',
 '522835',
 '522836',
 '1222240',
 '13177529',
 '1720257',
 '2257365',
 '13558213',
 '24742803',
 '775292',
 '30700984',
 '1272038',
 '7156792',
 '959663',
 '1555969',
 '22605867',
 '6639509',
 '10705914',
 '11212',
 '17344199',
 '13142341',
 '821682',
 '8491529',
 '705212',
 '1254774',
 '8580683',
 '17901445',
 '1738831',
 '704871',
 '704877',
 '552496',
 '128076',
 '229402',
 '22521931',
 '2092897',
 '3028840',
 '3028841',
 '24826364',
 '24826360',
 '10218995',
 '1026806',
 '24921383',
 '12086014',
 '17736343',
 '9219760',
 '8649238',
 '23177623',
 '6294151',
 '25538499',
 '30353202',
 '3998688',
 '15807807',
 '17839595',
 '1426096',
 '2673808',
 '7040441',
 '14623094',
 '13413481',
 '898109',
 '23316517',
 '1251411',
 '6555021',
 '9526813',
 '26127936',
 '6990114',
 '2336665',
 '2336667',
 '9562614',
 '652727',
 '2049769',
 '13497108',
 '31144646',
 '20816032',
 '25170708',
 '15818015',
 '1251990',
 '1251991',
 '7928027',
 '2880601',
 '23464600',
 '25365812',
 '7707352',
 '9513597',
 '5024306',
 '5395061',
 '20412413',
 '9316832',
 '21792868',
 '18668883',
 '16052994',
 '1038771',
 '1038770',
 '9888835',
 '1256965',
 '32455067',
 '17934375',
 '57628',
 '16125131',
 '7920491',
 '18806887',
 '231506',
 '2118849',
 '6082601',
 '17161730',
 '18747126',
 '3299927',
 '11255697',
 '16065848',
 '6061538',
 '2237666',
 '14451574',
 '28399149',
 '30051174',
 '22119411',
 '118251',
 '515187',
 '515188',
 '29585426',
 '9264003',
 '584302',
 '6716412',
 '1098517',
 '10831770',
 '6631139',
 '26047380',
 '5409334',
 '9828871',
 '22803099',
 '18430690',
 '979130',
 '410384',
 '23332954',
 '125445',
 '20724452',
 '620722',
 '6793355',
 '841152',
 '508152',
 '221070',
 '8049961',
 '1300420',
 '25075649',
 '16085464',
 '1842711',
 '24551752',
 '871377',
 '44540',
 '1008582',
 '2046895',
 '10451185',
 '1822671',
 '18144591',
 '9964335',
 '4376512',
 '27398274',
 '35991559',
 '17786758',
 '1403',
 '1402',
 '1407',
 '7573324',
 '12868912',
 '25799815',
 '2113235',
 '7713912',
 '22557366',
 '22557367',
 '22557362',
 '8066540',
 '17903346',
 '3133850',
 '3424399',
 '30968235',
 '27973402',
 '20663719',
 '20663713',
 '669757',
 '669756',
 '669758',
 '1215303',
 '6673292',
 '2726256',
 '6933611',
 '233511',
 '1514088',
 '6342596',
 '17303436',
 '949011',
 '2015003',
 '19134941',
 '24611612',
 '112116',
 '1408372',
 '112113',
 '29501140',
 '9759693',
 '8537348',
 '8471067',
 '8471063',
 '23015295',
 '26068847',
 '12776097',
 '6112293',
 '23010086',
 '8501974',
 '1065896',
 '25372669',
 '3781196',
 '6324757',
 '560724',
 '10365836',
 '23338036',
 '21929160',
 '797827',
 '22079475',
 '922650',
 '27063638',
 '3224278',
 '9717937',
 '17332350',
 '31163829',
 '1523825',
 '3396801',
 '17853404',
 '1934248',
 '1925441',
 '8329204',
 '134025',
 '134022',
 '9986814',
 '18371502',
 '18297487',
 '11715347',
 '1654354',
 '7458433',
 '19248',
 '20643228',
 '23010887',
 '1582977',
 '1341592',
 '15703291',
 '551635',
 '9719541',
 '15787122',
 '9796853',
 '574266',
 '771393',
 '7726965',
 '1735980',
 '6583290',
 '11178626',
 '34726646',
 '562694',
 '562695',
 '562692',
 '2866209',
 '1365226',
 '16670129',
 '27163259',
 '6296369',
 '2230540',
 '1200906',
 '640071',
 '640076',
 '3723660',
 '2752375',
 '22925392',
 '35134229',
 '17720',
 '11801718',
 '1284100',
 '30134',
 '30135',
 '616929',
 '5823509',
 '1471142',
 '13108400',
 '21956665',
 '23975704',
 '23129933',
 '7826319',
 '101994',
 '29940851',
 '732432',
 '28180232',
 '1528703',
 '13500593',
 '8747034',
 '29846912',
 '25209833',
 '34144419',
 '3468641',
 '34742460',
 '19439306',
 '6333916',
 '33946061',
 '23281518',
 '20784710',
 '13236914',
 '13236917',
 '538121',
 '767928',
 '9164724',
 '12919053',
 '691851',
 '16231961',
 '22747805',
 '11128816',
 '6396281',
 '968258',
 '10401869',
 '883273',
 '8513715',
 '45288',
 '45287',
 '7871115',
 '13504517',
 '25838967',
 '1846153',
 '15929363',
 '1473236',
 '19036440',
 '988745',
 '16457689',
 '24844468',
 '1074593',
 '1415440',
 '1415443',
 '7203615',
 '8489363',
 '25923056',
 '12344159',
 '26859679',
 '1121132',
 '17797845',
 '28195306',
 '23571304',
 '7799165',
 '1912859',
 '367563',
 '367568',
 '8454835',
 '25237638',
 '1288580',
 '6878432',
 '22628710',
 '21028697',
 '472703',
 '490079',
 '2319301',
 '18744759',
 '996467',
 '27178026',
 '11449884',
 '17976973',
 '253566',
 '6146898',
 '563814',
 '28455405',
 '24948186',
 '6392244',
 '375181',
 '375188',
 '23305136',
 '20698954',
 '16057492',
 '16057493',
 '17660097',
 '17660096',
 '17660095',
 '1586154',
 '28454653',
 '6555692',
 '1679579',
 '23080135',
 '23080133',
 '1853394',
 '355148',
 '2468383',
 '991745',
 '13516779',
 '14820395',
 '5216558',
 '128110',
 '25342649',
 '13219077',
 '17317860',
 '9874468',
 '16125596',
 '1989641',
 '13419480',
 '1450554',
 '1450556',
 '1948052',
 '1673887',
 '2817558',
 '1119451',
 '25700255',
 '29079250',
 '18261',
 '18263',
 '2050781',
 '21521682',
 '619979',
 '10674301',
 '1640276',
 '4855787',
 '7384912',
 '2265305',
 '3773251',
 '22580968',
 '24178192',
 '9748346',
 '29223203',
 '17804365',
 '12732514',
 '1171264',
 '13530219',
 '7232384',
 '12926785',
 '18656908',
 '2547418',
 '807765',
 '23016463',
 '22385843',
 '13632834',
 '1525659',
 '9474372',
 '10494282',
 '8115488',
 '16122350',
 '17231104',
 '590169',
 '1697163',
 '1697162',
 '1051423',
 '31821541',
 '19250236',
 '9905769',
 '1337053',
 '16069511',
 '9500018',
 '6394375',
 '5306469',
 '2180403',
 '172855',
 '172854',
 '172852',
 '172850',
 '5948328',
 '10059909',
 '14624561',
 '15953037',
 '18528280',
 '18528282',
 '1187364',
 '11019236',
 '105224',
 '22873968',
 '7274796',
 '1514966',
 '11545591',
 '17998354',
 '972086',
 '997544',
 '682673',
 '18803129',
 '16128012',
 '14760118',
 '653046',
 '653047',
 '35233251',
 '6617564',
 '3247828',
 '2024467',
 '8269434',
 '202159',
 '25983909',
 '1596869',
 '17262248',
 '29621148',
 '410289',
 '34459236',
 '15789206',
 '6254746',
 '1674098',
 '350097',
 '350098',
 '2362821',
 '28860166',
 '3789704',
 '168311',
 '7499712',
 '13262107',
 '6218924',
 '6218927',
 '29951347',
 '18367010',
 '19318323',
 '7455174',
 '11240752',
 '1008485',
 '267764',
 '1841749',
 '754965',
 '544867',
 '801560',
 '389058',
 '579444',
 '198633',
 '222383',
 '22087971',
 '2381145',
 '6533665',
 '398419',
 '28962764',
 '6617510',
 '11310833',
 '9670742',
 '10254949',
 '17703489',
 '22162514',
 '34224130',
 '27422409',
 '807673',
 '18467147',
 '8343867',
 '9960540',
 '17352796',
 '6606572',
 '15786699',
 '31667018',
 '32777867',
 '19016318',
 '13792330',
 '13792332',
 '297573',
 '2849211',
 '2711108',
 '233636',
 '24863830',
 '1081692',
 '403506',
 '403503',
 '17909016',
 '1871199',
 '23000512',
 '6478280',
 '13422873',
 '79521',
 '2104625',
 '7379604',
 '1056805',
 '20447824',
 '8199458',
 '9573751',
 '6413056',
 '661715',
 '4570613',
 '1337117',
 '6965880',
 '73905',
 ...]

In [11]:
genres = collection_genre.find({"book_id":{"$in":books_ids}},{"book_id": 1, "genres": 1, "_id": 0})

In [12]:
genres

In [12]:
genres = pd.DataFrame(list(genres))

In [14]:
genres.head()

    book_id                                             genres
0   1000018                                      {'poetry': 9}
1  10000259  {'poetry': 7, 'fiction': 3, 'history, historic...
2   1000032  {'poetry': 5, 'non-fiction': 4, 'fiction': 2, ...
3  10005124                                     {'poetry': 11}
4  10005166  {'poetry': 139, 'non-fiction': 1, 'romance': 0...

In [13]:
genres = pd.DataFrame(list(collection_genre.find(
    {"book_id": {"$in": books_ids}},
    {"book_id": 1, "genres": 1, "_id": 0}
)))

In [16]:
genres.head()

    book_id                                             genres
0   1000018                                      {'poetry': 9}
1  10000259  {'poetry': 7, 'fiction': 3, 'history, historic...
2   1000032  {'poetry': 5, 'non-fiction': 4, 'fiction': 2, ...
3  10005124                                     {'poetry': 11}
4  10005166  {'poetry': 139, 'non-fiction': 1, 'romance': 0...

In [14]:
merged = df.merge(genres, on="book_id", how="left")

In [15]:
merged.head()

,_id,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,...,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series,genres
0,69e8ac2044e2f3dc8aa255a6,,1,[],US,eng,"[{'count': '8', 'name': 'to-read'}, {'count': ...",,false,3.83,...,,1887,https://www.goodreads.com/book/show/16037549-v...,https://images.gr-assets.com/books/1348176637m...,16037549,3,5212748,Vision of Sir Launfal and Other Poems,Vision of Sir Launfal and Other Poems,{'poetry': 3}
1,69e8ac2044e2f3dc8aa255a7,0811223981,2,[],US,,"[{'count': '100', 'name': 'to-read'}, {'count'...",,false,3.83,...,,2015,https://www.goodreads.com/book/show/22466716-f...,https://images.gr-assets.com/books/1404958407m...,22466716,37,41905435,Fairy Tales: Dramolettes,Fairy Tales: Dramolettes,"{'poetry': 2, 'fiction': 2}"
2,69e8ac2044e2f3dc8aa255a8,0374428115,7,[],US,,"[{'count': '32', 'name': 'to-read'}, {'count':...",,false,4.38,...,,2008,https://www.goodreads.com/book/show/926662.Gro...,https://s.gr-assets.com/assets/nophoto/book/11...,926662,45,911665,Growltiger's Last Stand and Other Poems,Growltiger's Last Stand and Other Poems,"{'poetry': 10, 'children': 9, 'fiction': 1, 'n..."
3,69e8ac2044e2f3dc8aa255a9,0156182890,12,[],US,,"[{'count': '554', 'name': 'to-read'}, {'count'...",,false,3.71,...,,1964,https://www.goodreads.com/book/show/926667.The...,https://images.gr-assets.com/books/1382939971m...,926667,115,995066,The Cocktail Party,The Cocktail Party,"{'fiction': 30, 'poetry': 29}"
4,69e8ac2044e2f3dc8aa255aa,1942004192,4,[],US,eng,"[{'count': '228', 'name': 'to-read'}, {'count'...",,false,5.00,...,First,2015,https://www.goodreads.com/book/show/29065952-l...,https://images.gr-assets.com/books/1455198396m...,29065952,9,49294781,Louder Than Everything You Love,Louder Than Everything You Love,{'poetry': 2}

In [16]:
import numpy as np

In [17]:
def stable_softmax(x):
  z = x - np.max(x, axis=-1, keepdims=True)
  numerator = np.exp(z)
  denominator = np.sum(numerator, axis=-1, keepdims=True)
  return numerator/denominator

In [18]:
def normalisation(x):
  sum =  np.sum(x, axis=-1, keepdims=True)
  return x/sum

In [19]:
test_dict = {'poetry': 2, 'fiction': 2}
for value in test_dict:
  print(value)

poetry
fiction

In [20]:
def genre_normalisation(dic:dict):
  dic = dict(dic)
  arr = np.array(list(dic.values()))
  res = normalisation(arr)
  final = {}
  i=0
  for key in dic:
    final[key] = res[i]
    i+=1
  return final

In [21]:
genre_normalisation(test_dict)

{'poetry': np.float64(0.5), 'fiction': np.float64(0.5)}

In [22]:
merged["genres"] = merged["genres"].apply(genre_normalisation)

In [38]:
merged.columns

Index(['_id', 'isbn', 'text_reviews_count', 'series', 'country_code',
       'language_code', 'popular_shelves', 'asin', 'is_ebook',
       'average_rating', 'kindle_asin', 'similar_books', 'description',
       'format', 'link', 'authors', 'publisher', 'num_pages',
       'publication_day', 'isbn13', 'publication_month', 'edition_information',
       'publication_year', 'url', 'image_url', 'book_id', 'ratings_count',
       'work_id', 'title', 'title_without_series', 'genres'],
      dtype='object')

In [39]:
merged["url"]

0        https://www.goodreads.com/book/show/16037549-v...
1        https://www.goodreads.com/book/show/22466716-f...
2        https://www.goodreads.com/book/show/926662.Gro...
3        https://www.goodreads.com/book/show/926667.The...
4        https://www.goodreads.com/book/show/29065952-l...
                               ...
36509    https://www.goodreads.com/book/show/9874488-ta...
36510    https://www.goodreads.com/book/show/7657489-a-...
36511    https://www.goodreads.com/book/show/3762261-su...
36512    https://www.goodreads.com/book/show/23452091-o...
36513    https://www.goodreads.com/book/show/2342551.Th...
Name: url, Length: 36514, dtype: object

In [23]:
merged = merged.drop(columns=["url", "image_url"])

In [41]:
merged.columns

Index(['_id', 'isbn', 'text_reviews_count', 'series', 'country_code',
       'language_code', 'popular_shelves', 'asin', 'is_ebook',
       'average_rating', 'kindle_asin', 'similar_books', 'description',
       'format', 'link', 'authors', 'publisher', 'num_pages',
       'publication_day', 'isbn13', 'publication_month', 'edition_information',
       'publication_year', 'book_id', 'ratings_count', 'work_id', 'title',
       'title_without_series', 'genres'],
      dtype='object')

In [43]:
merged["popular_shelves"][0]

[{'count': '8', 'name': 'to-read'},
 {'count': '3', 'name': 'poetry'},
 {'count': '2', 'name': 'currently-reading'},
 {'count': '1', 'name': '01-kindle'},
 {'count': '1', 'name': 'real-books'},
 {'count': '1', 'name': 'personal-library'}]

In [24]:
shelf_counts = {}
for shelves in merged["popular_shelves"]:
    if not shelves:
        continue
    for s in shelves:
        name = s["name"]
        shelf_counts[name] = shelf_counts.get(name, 0) + int(s["count"])

shelf_df = (
    pd.DataFrame(shelf_counts.items(), columns=["shelf", "total_count"])
    .sort_values("total_count", ascending=False)
    .reset_index(drop=True)
)

In [52]:
shelf_df

                                      shelf  total_count
0                                   to-read     97449512
1                                  classics      6917351
2                                    poetry      5468202
3                         currently-reading      2464098
4                                   fiction      2140820
...                                     ...          ...
120545  flames-on-the-side-of-my-face-hated            1
120546                homophobic-undertones            1
120547                   offensive-ignorant            1
120548                     so-much-bullsh-t            1
120549              some-heteronormative-bs            1

[120550 rows x 2 columns]

In [56]:
shelf_df[50:100]

                        shelf  total_count
50             school-reading        96106
51                classic-lit        94072
52                      ebook        92927
53                epic-poetry        92459
54                  wish-list        92297
55           to-read-classics        91650
56           required-reading        91489
57                    tragedy        90057
58                     greece        89828
59            classic-fiction        89567
60                shakespeare        86773
61             read-in-school        85460
62                      epics        85071
63     rory-gilmore-challenge        84478
64                    re-read        82426
65                        war        81977
66                 nonfiction        81853
67                 to-re-read        78336
68               the-classics        78133
69               home-library        77663
70                   children        76007
71                     ebooks        75150
72                    theater        74828
73             ancient-greece        74687
74                  my-ebooks        74568
75                   literary        72830
76                 translated        72430
77                      poems        71121
78                 unfinished        70669
79              adult-fiction        69084
80              short-stories        68614
81               rory-gilmore        66907
82                 children-s        65165
83                      books        65022
84         all-time-favorites        64792
85                        lit        64059
86           children-s-books        62453
87                  spiritual        61317
88                  audiobook        60688
89                young-adult        60506
90                  antiquity        59446
91                  bookshelf        59286
92            greek-mythology        56712
93                    italian        56244
94                   medieval        55811
95                     poesia        54143
96  rory-gilmore-reading-list        52685
97       classical-literature        51998
98           literary-fiction        49972
99                      humor        49942

In [73]:
STOPLIST = {
    "to-read", "currently-reading", "read", "owned", "own", "books-i-own",
    "favorites", "my-books", "default", "kindle", "ebook", "ebooks",
    "audiobook", "audio", "library", "wishlist", "want-to-read",
    "did-not-finish", "dnf", "abandoned", "general", "shelfari-favorites",
    "all", "maybe", "re-read", "new", "recommended","owned-books", "to-buy", "my-library", "i-own", "required-reading", "required-reading", "home-library", "my-ebooks", "to-re-read"
}

shelves_filtered = shelf_df[~shelf_df["shelf"].isin(STOPLIST)]

In [74]:
shelves_filtered.head(60)

                             shelf  total_count
1                         classics      6917351
2                           poetry      5468202
4                          fiction      2140820
6                          classic      1202721
8                           school       843946
9                        mythology       813294
10                      literature       806881
12                         fantasy       556208
13                      philosophy       404777
14                         history       324184
16                      for-school       286282
18                     high-school       254411
20              classic-literature       247292
21              historical-fiction       238512
22                 read-for-school       232642
23                        religion       232361
24                     non-fiction       228927
25                            epic       220805
26                      historical       213431
27                       adventure       195161
30                           plays       185615
31                      favourites       174779
32                           greek       173444
34                           adult       163361
35  rory-gilmore-reading-challenge       157076
36                classics-to-read       150181
37                         college       148535
38                    school-books       148354
39                       classical       138056
41                          novels       125868
43                       childrens       116868
44                         ancient       114368
45                    spirituality       113202
46                           drama       110552
47                    school-reads       107902
48                        clàssics       104027
49                          own-it       100897
50                  school-reading        96106
51                     classic-lit        94072
53                     epic-poetry        92459
54                       wish-list        92297
55                to-read-classics        91650
57                         tragedy        90057
58                          greece        89828
59                 classic-fiction        89567
60                     shakespeare        86773
61                  read-in-school        85460
62                           epics        85071
63          rory-gilmore-challenge        84478
65                             war        81977
66                      nonfiction        81853
68                    the-classics        78133
70                        children        76007
72                         theater        74828
73                  ancient-greece        74687
75                        literary        72830
76                      translated        72430
77                           poems        71121
78                      unfinished        70669
79                   adult-fiction        69084

In [75]:
shelves_filtered = shelves_filtered[:60]

In [76]:
shelf_list = list(shelves_filtered["shelf"])

In [77]:
shelf_list

['classics',
 'poetry',
 'fiction',
 'classic',
 'school',
 'mythology',
 'literature',
 'fantasy',
 'philosophy',
 'history',
 'for-school',
 'high-school',
 'classic-literature',
 'historical-fiction',
 'read-for-school',
 'religion',
 'non-fiction',
 'epic',
 'historical',
 'adventure',
 'plays',
 'favourites',
 'greek',
 'adult',
 'rory-gilmore-reading-challenge',
 'classics-to-read',
 'college',
 'school-books',
 'classical',
 'novels',
 'childrens',
 'ancient',
 'spirituality',
 'drama',
 'school-reads',
 'clàssics',
 'own-it',
 'school-reading',
 'classic-lit',
 'epic-poetry',
 'wish-list',
 'to-read-classics',
 'tragedy',
 'greece',
 'classic-fiction',
 'shakespeare',
 'read-in-school',
 'epics',
 'rory-gilmore-challenge',
 'war',
 'nonfiction',
 'the-classics',
 'children',
 'theater',
 'ancient-greece',
 'literary',
 'translated',
 'poems',
 'unfinished',
 'adult-fiction']

In [78]:
def filter_shelves(shelves, keep_set):
    if not shelves:
        return []
    return [s for s in shelves if s["name"] in keep_set]

In [79]:
KEEP = set(shelf_list)

In [89]:
KEEP

{'adult',
 'adult-fiction',
 'adventure',
 'ancient',
 'ancient-greece',
 'children',
 'childrens',
 'classic',
 'classic-fiction',
 'classic-lit',
 'classic-literature',
 'classical',
 'classics',
 'classics-to-read',
 'clàssics',
 'college',
 'drama',
 'epic',
 'epic-poetry',
 'epics',
 'fantasy',
 'favourites',
 'fiction',
 'for-school',
 'greece',
 'greek',
 'high-school',
 'historical',
 'historical-fiction',
 'history',
 'literary',
 'literature',
 'mythology',
 'non-fiction',
 'nonfiction',
 'novels',
 'own-it',
 'philosophy',
 'plays',
 'poems',
 'poetry',
 'read-for-school',
 'read-in-school',
 'religion',
 'rory-gilmore-challenge',
 'rory-gilmore-reading-challenge',
 'school',
 'school-books',
 'school-reading',
 'school-reads',
 'shakespeare',
 'spirituality',
 'the-classics',
 'theater',
 'to-read-classics',
 'tragedy',
 'translated',
 'unfinished',
 'war',
 'wish-list'}

In [90]:
merged["popular_shelves"] = merged["popular_shelves"].apply(lambda s: filter_shelves(s, KEEP))

In [91]:
def normalize_shelves(shelves):
    if not shelves:
        return []
    total = sum(int(s["count"]) for s in shelves)
    if total == 0:
        return []
    return [{"name": s["name"], "weight": int(s["count"]) / total} for s in shelves]

In [92]:
merged["popular_shelves"] = merged["popular_shelves"].apply(normalize_shelves)

In [93]:
n_no_shelf = merged["popular_shelves"].apply(lambda s: not s).sum()
print(f"books with no shelves: {n_no_shelf} ({n_no_shelf / len(df):.1%})")

books with no shelves: 88 (0.2%)

In [25]:
df=merged

In [35]:
from neo4j import GraphDatabase

In [36]:
driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "Niveau99"))

In [98]:
# 1. Indexes first (idempotent, cheap)
def create_indexes(tx):
    tx.run("CREATE INDEX genre_name_idx IF NOT EXISTS FOR (g:Genre) ON (g.name)")
    tx.run("CREATE INDEX shelf_name_idx IF NOT EXISTS FOR (s:Shelf) ON (s.name)")

# 2. Node creation
def create_genre_nodes(tx, names):
    tx.run("""
        UNWIND $names AS n
        MERGE (:Genre {name: n})
    """, names=names)

def create_shelf_nodes(tx, names):
    tx.run("""
        UNWIND $names AS n
        MERGE (:Shelf {name: n})
    """, names=names)

In [101]:
genre_names = sorted({g for genres in df["genres"] for g in genres})
shelf_names = sorted({s["name"] for shelves in df["popular_shelves"] for s in shelves})

In [102]:
# 4. Run
with driver.session(database="goodreads-poetry") as session:
    session.execute_write(create_indexes)
    session.execute_write(create_genre_nodes, genre_names)
    session.execute_write(create_shelf_nodes, shelf_names)

print(f"created {len(genre_names)} genres, {len(shelf_names)} shelves")

created 10 genres, 60 shelves

In [105]:
def create_book_nodes(tx, books):
    tx.run("""
        UNWIND $books AS b
        MERGE (book:Book {book_id: b.book_id})
        SET book.isbn = b.isbn,
            book.isbn13 = b.isbn13,
            book.asin = b.asin,
            book.kindle_asin = b.kindle_asin,
            book.text_reviews_count = b.text_reviews_count,
            book.ratings_count = b.ratings_count,
            book.average_rating = b.average_rating,
            book.country_code = b.country_code,
            book.language_code = b.language_code,
            book.is_ebook = b.is_ebook,
            book.description = b.description,
            book.format = b.format,
            book.link = b.link,
            book.publisher = b.publisher,
            book.num_pages = b.num_pages,
            book.publication_day = b.publication_day,
            book.publication_month = b.publication_month,
            book.publication_year = b.publication_year,
            book.edition_information = b.edition_information,
            book.work_id = b.work_id,
            book.title = b.title,
            book.title_without_series = b.title_without_series
    """, books=books)

In [109]:
def create_book_index(tx):
    tx.run("CREATE INDEX book_id_idx IF NOT EXISTS FOR (b:Book) ON (b.book_id)")

In [40]:
def chunked(seq, n):
    for i in range(0, len(seq), n):
        yield seq[i:i + n]

In [106]:
# Numeric coercion (raw values are strings)
df["publication_year"] = pd.to_numeric(df["publication_year"], errors="coerce")
df["publication_month"] = pd.to_numeric(df["publication_month"], errors="coerce")
df["publication_day"] = pd.to_numeric(df["publication_day"], errors="coerce")
df["average_rating"] = pd.to_numeric(df["average_rating"], errors="coerce")
df["ratings_count"] = pd.to_numeric(df["ratings_count"], errors="coerce")
df["text_reviews_count"] = pd.to_numeric(df["text_reviews_count"], errors="coerce")
df["num_pages"] = pd.to_numeric(df["num_pages"], errors="coerce")
df["is_ebook"] = df["is_ebook"].map({"true": True, "false": False})

In [107]:
cols = [
    "book_id", "isbn", "isbn13", "asin", "kindle_asin",
    "text_reviews_count", "ratings_count", "average_rating",
    "country_code", "language_code", "is_ebook",
    "description", "format", "link",
    "publisher", "num_pages",
    "publication_day", "publication_month", "publication_year",
    "edition_information", "work_id",
    "title", "title_without_series",
]

In [108]:
books_payload = (
    df[cols]
    .astype(object)
    .where(lambda x: x.notna(), None)
    .to_dict("records")
)

In [115]:
with driver.session(database="goodreads-poetry") as session:
    session.execute_write(create_book_index)  # if not already created
    for chunk in chunked(books_payload, 10_000):
        session.execute_write(create_book_nodes, chunk)

print(f"created {len(books_payload)} book nodes")

created 36514 book nodes

In [112]:
def create_genre_edges(tx, edges):
    tx.run("""
        UNWIND $edges AS e
        MATCH (b:Book {book_id: e.book_id})
        MATCH (g:Genre {name: e.genre})
        MERGE (b)-[r:HAS_GENRE]->(g)
        SET r.weight = e.weight
    """, edges=edges)

def create_shelf_edges(tx, edges):
    tx.run("""
        UNWIND $edges AS e
        MATCH (b:Book {book_id: e.book_id})
        MATCH (s:Shelf {name: e.shelf})
        MERGE (b)-[r:HAS_SHELF]->(s)
        SET r.weight = e.weight
    """, edges=edges)

In [113]:
# Flatten the per-book lists into edge records
genre_edges = [
    {"book_id": row.book_id, "genre": g, "weight": w}
    for row in df.itertuples()
    for g, w in row.genres.items()  # adapt: depends on whether genres is dict or list-of-dicts
]

shelf_edges = [
    {"book_id": row.book_id, "shelf": s["name"], "weight": s["weight"]}
    for row in df.itertuples()
    for s in row.popular_shelves
]

In [117]:
with driver.session(database="goodreads-poetry") as session:
    for chunk in chunked(genre_edges, 10_000):
        session.execute_write(create_genre_edges, chunk)
    for chunk in chunked(shelf_edges, 10_000):
        session.execute_write(create_shelf_edges, chunk)

In [118]:
from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017")
goodreads_db = client["goodreads"]

# Unique work_ids from your books
work_ids = df["work_id"].dropna().astype(str).unique().tolist()
print(f"need to fetch {len(work_ids)} unique works")

# Pull from Mongo in one shot — 36K-ish ids fits well under the 16MB BSON limit
works_cursor = goodreads_db.works.find(
    {"work_id": {"$in": work_ids}},
    {"_id": 0}  # drop the ObjectId, keep everything else
)
works_df = pd.DataFrame(list(works_cursor))

print(f"got {len(works_df)} works")
print(f"missing: {len(work_ids) - len(works_df)}")

need to fetch 25552 unique works
got 25552 works
missing: 0

In [119]:
def parse_rating_dist(s):
    """'5:1|4:1|3:1|2:0|1:0|total:3' -> dict"""
    if not s:
        return None
    parts = dict(p.split(":") for p in s.split("|"))
    return {k: int(v) for k, v in parts.items()}

works_df["rating_dist_parsed"] = works_df["rating_dist"].apply(parse_rating_dist)

# Numeric coercion
for col in ["books_count", "reviews_count", "text_reviews_count",
            "ratings_count", "ratings_sum",
            "original_publication_year", "original_publication_month",
            "original_publication_day"]:
    works_df[col] = pd.to_numeric(works_df[col], errors="coerce")

In [120]:
def expand_rating_dist(rd):
    if not rd:
        return {"rd_5": None, "rd_4": None, "rd_3": None, "rd_2": None, "rd_1": None, "rd_total": None}
    return {
        "rd_5": rd.get("5"), "rd_4": rd.get("4"), "rd_3": rd.get("3"),
        "rd_2": rd.get("2"), "rd_1": rd.get("1"), "rd_total": rd.get("total"),
    }

rd_expanded = pd.DataFrame(works_df["rating_dist_parsed"].apply(expand_rating_dist).tolist())
works_df = pd.concat([works_df, rd_expanded], axis=1)

In [123]:
def create_work_index(tx):
    tx.run("CREATE INDEX work_id_idx IF NOT EXISTS FOR (w:Work) ON (w.work_id)")

def create_work_nodes(tx, works):
    tx.run("""
        UNWIND $works AS w
        MERGE (work:Work {work_id: w.work_id})
        SET work.original_title = w.original_title,
            work.best_book_id = w.best_book_id,
            work.original_publication_year = w.original_publication_year,
            work.original_publication_month = w.original_publication_month,
            work.original_publication_day = w.original_publication_day,
            work.original_language_id = w.original_language_id,
            work.default_description_language_code = w.default_description_language_code,
            work.default_chaptering_book_id = w.default_chaptering_book_id,
            work.media_type = w.media_type,
            work.books_count = w.books_count,
            work.reviews_count = w.reviews_count,
            work.text_reviews_count = w.text_reviews_count,
            work.ratings_count = w.ratings_count,
            work.ratings_sum = w.ratings_sum,
            work.rating_dist = w.rating_dist,
            work.rd_5 = w.rd_5,
            work.rd_4 = w.rd_4,
            work.rd_3 = w.rd_3,
            work.rd_2 = w.rd_2,
            work.rd_1 = w.rd_1,
            work.rd_total = w.rd_total
    """, works=works)

work_cols = [
    "work_id", "best_book_id", "original_title",
    "original_publication_year", "original_publication_month", "original_publication_day",
    "original_language_id", "default_description_language_code", "default_chaptering_book_id",
    "media_type", "books_count", "reviews_count", "text_reviews_count",
    "ratings_count", "ratings_sum", "rating_dist",
    "rd_5", "rd_4", "rd_3", "rd_2", "rd_1", "rd_total",
]

works_payload = (
    works_df[work_cols]
    .astype(object)
    .where(lambda x: x.notna(), None)
    .to_dict("records")
)

with driver.session(database="goodreads-poetry") as session:
    session.execute_write(create_work_index)
    for chunk in chunked(works_payload, 10_000):
        session.execute_write(create_work_nodes, chunk)

print(f"created {len(works_payload)} work nodes")

created 25552 work nodes

In [125]:
def create_edition_of_edges(tx, edges):
    tx.run("""
        UNWIND $edges AS e
        MATCH (b:Book {book_id: e.book_id})
        MATCH (w:Work {work_id: e.work_id})
        MERGE (b)-[:EDITION_OF]->(w)
    """, edges=edges)

edition_edges = (
    df[["book_id", "work_id"]]
    .dropna()
    .astype(str)
    .to_dict("records")
)

with driver.session(database="goodreads-poetry") as session:
    for chunk in chunked(edition_edges, 10_000):
        session.execute_write(create_edition_of_edges, chunk)

print(f"created {len(edition_edges)} edition_of edges")

created 36514 edition_of edges

In [126]:
df["authors"]

0                     [{'author_id': '15585', 'role': ''}]
1        [{'author_id': '16073', 'role': ''}, {'author_...
2        [{'author_id': '18540', 'role': ''}, {'author_...
3                     [{'author_id': '18540', 'role': ''}]
4                  [{'author_id': '14308759', 'role': ''}]
                               ...
36509               [{'author_id': '4502880', 'role': ''}]
36510                   [{'author_id': '142', 'role': ''}]
36511               [{'author_id': '1023504', 'role': ''}]
36512                   [{'author_id': '903', 'role': ''}]
36513           [{'author_id': '82312', 'role': 'Editor'}]
Name: authors, Length: 36514, dtype: object

In [38]:
DB_NAME = "goodreads-poetry"

In [128]:
# Collect unique author_ids across all books
author_ids = sorted({
    a["author_id"]
    for authors in df["authors"]
    for a in (authors or [])
})
print(f"need to fetch {len(author_ids)} unique authors")

authors_cursor = goodreads_db.authors.find(
    {"author_id": {"$in": author_ids}},
    {"_id": 0}
)
authors_df = pd.DataFrame(list(authors_cursor))
print(f"got {len(authors_df)} authors")
print(f"missing: {len(author_ids) - len(authors_df)}")

need to fetch 23105 unique authors
got 23105 authors
missing: 0

In [129]:
for col in ["average_rating", "ratings_count", "text_reviews_count"]:
    authors_df[col] = pd.to_numeric(authors_df[col], errors="coerce")

def create_author_index(tx):
    tx.run("CREATE INDEX author_id_idx IF NOT EXISTS FOR (a:Author) ON (a.author_id)")

def create_author_nodes(tx, authors):
    tx.run("""
        UNWIND $authors AS a
        MERGE (author:Author {author_id: a.author_id})
        SET author.name = a.name,
            author.average_rating = a.average_rating,
            author.ratings_count = a.ratings_count,
            author.text_reviews_count = a.text_reviews_count
    """, authors=authors)

author_cols = ["author_id", "name", "average_rating", "ratings_count", "text_reviews_count"]
authors_payload = (
    authors_df[author_cols]
    .astype(object)
    .where(lambda x: x.notna(), None)
    .to_dict("records")
)

with driver.session(database=DB_NAME) as session:
    session.execute_write(create_author_index)
    for chunk in chunked(authors_payload, 10_000):
        session.execute_write(create_author_nodes, chunk)

print(f"created {len(authors_payload)} author nodes")

created 23105 author nodes

In [130]:
def create_authored_by_edges(tx, edges):
    tx.run("""
        UNWIND $edges AS e
        MATCH (b:Book {book_id: e.book_id})
        MATCH (a:Author {author_id: e.author_id})
        MERGE (b)-[r:AUTHORED_BY]->(a)
        SET r.role = e.role,
            r.position = e.position
    """, edges=edges)

authored_edges = [
    {
        "book_id": str(row.book_id),
        "author_id": a["author_id"],
        "role": a.get("role", "") or None,  # store None for empty roles
        "position": i,                       # 0 = first author, 1 = second, etc.
    }
    for row in df.itertuples()
    for i, a in enumerate(row.authors or [])
]

print(f"prepared {len(authored_edges)} authored_by edges")

with driver.session(database=DB_NAME) as session:
    for chunk in chunked(authored_edges, 10_000):
        session.execute_write(create_authored_by_edges, chunk)

prepared 58127 authored_by edges

In [131]:
poetry_db = client["poetry"]  # the database name you mentioned

book_ids = df["book_id"].astype(str).unique().tolist()
print(f"filtering reviews for {len(book_ids)} books")

# Pull in batches of book_ids to keep $in queries reasonable
BATCH = 5000
reviews_chunks = []
for i in range(0, len(book_ids), BATCH):
    chunk_ids = book_ids[i:i + BATCH]
    cursor = poetry_db.reviews.find(
        {"book_id": {"$in": chunk_ids}},
        {"_id": 0}
    )
    reviews_chunks.append(pd.DataFrame(list(cursor)))

reviews_df = pd.concat(reviews_chunks, ignore_index=True)
print(f"got {len(reviews_df)} reviews")
print(f"unique users: {reviews_df['user_id'].nunique()}")
print(f"unique books with reviews: {reviews_df['book_id'].nunique()}")

filtering reviews for 36514 books
got 154555 reviews
unique users: 47400
unique books with reviews: 36412

In [30]:
def parse_gr_date(s):
    if not s or pd.isna(s):
        return None
    try:
        return pd.to_datetime(s, format="%a %b %d %H:%M:%S %z %Y")
    except (ValueError, TypeError):
        return None

In [ ]:


for col in ["date_added", "date_updated", "read_at", "started_at"]:
    reviews_df[col] = reviews_df[col].apply(parse_gr_date)

# Numeric coercion
for col in ["rating", "n_votes", "n_comments"]:
    reviews_df[col] = pd.to_numeric(reviews_df[col], errors="coerce")

# Strip empty review_text → None (your spec drops these for the Review node, see below)
reviews_df["review_text"] = reviews_df["review_text"].replace("", None)

In [42]:
def create_user_index(tx):
    tx.run("CREATE INDEX user_id_idx IF NOT EXISTS FOR (u:User) ON (u.user_id)")

def create_user_nodes(tx, users):
    tx.run("""
        UNWIND $users AS u
        MERGE (:User {user_id: u})
    """, users=users)

In [ ]:


# Users come from BOTH reviews and interactions — for now just reviews; you'll union with
# interactions when you load those next.
user_ids = reviews_df["user_id"].unique().tolist()
print(f"creating {len(user_ids)} user nodes")

with driver.session(database=DB_NAME) as session:
    session.execute_write(create_user_index)
    for chunk in chunked(user_ids, 10_000):
        session.execute_write(create_user_nodes, chunk)

creating 47400 user nodes

In [134]:
reviews_with_text = reviews_df[reviews_df["review_text"].notna()].copy()
print(f"keeping {len(reviews_with_text)} reviews with text "
      f"(dropped {len(reviews_df) - len(reviews_with_text)} empty)")

def create_review_index(tx):
    tx.run("CREATE INDEX review_id_idx IF NOT EXISTS FOR (r:Review) ON (r.review_id)")

def create_review_nodes(tx, reviews):
    tx.run("""
        UNWIND $reviews AS r
        MERGE (review:Review {review_id: r.review_id})
        SET review.rating = r.rating,
            review.n_votes = r.n_votes,
            review.n_comments = r.n_comments,
            review.date_added = r.date_added,
            review.date_updated = r.date_updated,
            review.read_at = r.read_at,
            review.started_at = r.started_at
    """, reviews=reviews)

# Note: NOT storing review_text on the node — it goes to HDF5 for embedding (spec §4.2, §8.4)
review_cols = [
    "review_id", "rating", "n_votes", "n_comments",
    "date_added", "date_updated", "read_at", "started_at",
]

reviews_payload = (
    reviews_with_text[review_cols]
    .astype(object)
    .where(lambda x: x.notna(), None)
    .to_dict("records")
)

with driver.session(database=DB_NAME) as session:
    session.execute_write(create_review_index)
    for chunk in chunked(reviews_payload, 10_000):
        session.execute_write(create_review_nodes, chunk)

print(f"created {len(reviews_payload)} review nodes")

keeping 154392 reviews with text (dropped 163 empty)
created 154392 review nodes

In [135]:
def create_wrote_edges(tx, edges):
    tx.run("""
        UNWIND $edges AS e
        MATCH (u:User {user_id: e.user_id})
        MATCH (r:Review {review_id: e.review_id})
        MERGE (u)-[:WROTE]->(r)
    """, edges=edges)

def create_reviews_edges(tx, edges):
    tx.run("""
        UNWIND $edges AS e
        MATCH (r:Review {review_id: e.review_id})
        MATCH (b:Book {book_id: e.book_id})
        MERGE (r)-[:REVIEWS]->(b)
    """, edges=edges)

wrote_edges = reviews_with_text[["user_id", "review_id"]].to_dict("records")
reviews_edges = reviews_with_text[["review_id", "book_id"]].astype(str).to_dict("records")

with driver.session(database=DB_NAME) as session:
    for chunk in chunked(wrote_edges, 10_000):
        session.execute_write(create_wrote_edges, chunk)
    for chunk in chunked(reviews_edges, 10_000):
        session.execute_write(create_reviews_edges, chunk)

In [28]:
# ----- 1. Pull interactions for our books -----------------------------------

poetry_db = client["poetry"]

book_ids = df["book_id"].astype(str).unique().tolist()
print(f"filtering interactions for {len(book_ids)} books")

BATCH = 5000
interactions_chunks = []
for i in range(0, len(book_ids), BATCH):
    chunk_ids = book_ids[i:i + BATCH]
    cursor = poetry_db.interactions.find(
        {"book_id": {"$in": chunk_ids}},
        {
            "_id": 0,
            "user_id": 1, "book_id": 1, "review_id": 1,
            "is_read": 1, "rating": 1, "date_added": 1,
        }
    )
    interactions_chunks.append(pd.DataFrame(list(cursor)))

interactions_df = pd.concat(interactions_chunks, ignore_index=True)
print(f"got {len(interactions_df)} interactions")
print(f"unique users: {interactions_df['user_id'].nunique()}")

filtering interactions for 36514 books
got 2734350 interactions
unique users: 377799

In [32]:
interactions_df["rating"] = pd.to_numeric(interactions_df["rating"], errors="coerce").fillna(0).astype(int)
interactions_df["is_read"] = interactions_df["is_read"].astype(bool)
interactions_df["book_id"] = interactions_df["book_id"].astype(str)
interactions_df["date_added"] = interactions_df["date_added"].apply(parse_gr_date)
interactions_df["date_added"] = pd.to_datetime(
    interactions_df["date_added"],
    format="%a %b %d %H:%M:%S %z %Y",
    errors="coerce",
    utc=True,  # normalize all timezones to UTC so the column has a uniform tz
)
interactions_df["date_added"] = interactions_df["date_added"].dt.strftime("%Y-%m-%dT%H:%M:%S%z")
interactions_df["date_added"] = interactions_df["date_added"].where(interactions_df["date_added"].notna(), None)

def assign_edge_type(row):
    if row["is_read"]:
        if row["rating"] >= 4:
            return "RATED_HIGH"
        if row["rating"] >= 1:
            return "RATED_LOW"
        return "READ_UNRATED"
    return "SHELVED"  # is_read=false, rating=0 by elimination

interactions_df["edge_type"] = interactions_df.apply(assign_edge_type, axis=1)

print("\nedge type distribution:")
print(interactions_df["edge_type"].value_counts())

edge type distribution:
edge_type
SHELVED         1420740
RATED_HIGH       906536
RATED_LOW        322523
READ_UNRATED      84551
Name: count, dtype: int64

In [45]:
all_user_ids = interactions_df["user_id"].unique().tolist()
print(f"\nensuring {len(all_user_ids)} user nodes exist")

with driver.session(database=DB_NAME) as session:
    for chunk in chunked(all_user_ids, 10_000):
        session.execute_write(create_user_nodes, chunk)  # MERGE is idempotent

ensuring 377799 user nodes exist

In [46]:
def create_user_book_edges(tx, edges, edge_type):
    # Edge type can't be a Cypher parameter — must be string-formatted.
    # Safe because edge_type is from a fixed allowlist below.
    tx.run(f"""
        UNWIND $edges AS e
        MATCH (u:User {{user_id: e.user_id}})
        MATCH (b:Book {{book_id: e.book_id}})
        MERGE (u)-[r:{edge_type}]->(b)
        SET r.rating = e.rating,
            r.date_added = e.date_added
    """, edges=edges)

ALLOWED_EDGE_TYPES = {"RATED_HIGH", "RATED_LOW", "READ_UNRATED", "SHELVED"}
edge_cols = ["user_id", "book_id", "rating", "date_added"]

for edge_type, group in interactions_df.groupby("edge_type"):
    assert edge_type in ALLOWED_EDGE_TYPES, f"unexpected edge type: {edge_type}"
    edges = (
        group[edge_cols]
        .astype(object)
        .where(lambda x: x.notna(), None)
        .to_dict("records")
    )
    print(f"creating {len(edges):>8d} {edge_type} edges...")
    with driver.session(database=DB_NAME) as session:
        for chunk in chunked(edges, 10_000):
            session.execute_write(create_user_book_edges, chunk, edge_type)

print("\ndone")

creating   906536 RATED_HIGH edges...
creating   322523 RATED_LOW edges...
creating    84551 READ_UNRATED edges...
creating  1420740 SHELVED edges...

done